name: scanbot_barcode_sdk_example
description: "Scanbot Barcode Scanner SDK Example App for Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  barcode_scanner: ^9.0.0
  image_picker: ^1.2.3
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.3
  file_picker: ^13.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true