name: scanbot_barcode_sdk_example
description: Scanbot Barcode Scanner SDK Example App for Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.14.0-0 <3.0.0'
  flutter: ^2.0.1

dependencies:
  flutter:
    sdk: flutter

  # Scanbot Barcode Scanner SDK
  barcode_scanner: ^3.2.4-beta1

  path_provider: ^2.0.15
  scanbot_image_picker: ^1.0.0
  cupertino_icons: ^1.0.2
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
